name: CD Pipeline - Deploy to Azure Web App

on:
  push:
    branches:
      - main



jobs:
  deploy:
    needs: docker-build-push   # This assumes you have a separate job that builds & pushes Docker image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Deploy Docker image to Azure Web App
      - name: Deploy to Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <your-azure-webapp-name>      # Replace with your Web App name
          images: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest


