name: Terraform CI/CD to deploy Infrastructure on Azure

on:
  push:
    branches:
      - main

jobs:
  terraform:  # Fixed indentation
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
      ARM_CLIENT_ID:       ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
      ARM_CLIENT_SECRET:   ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
      ARM_TENANT_ID:       ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}

      TF_VAR_subscription_id: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
      TF_VAR_client_id:       ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
      TF_VAR_client_secret:   ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
      TF_VAR_tenant_id:       ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      #Todo: Add Logic to Azure Step

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./Terraform_pipeline

      - name: Terraform format  # Fixed spelling and indentation
        run: terraform fmt -check
        working-directory: ./Terraform_pipeline

      - name: Validate Terraform
        run: terraform validate
        working-directory: ./Terraform_pipeline
        
      - name: Plan Infrastructure Changes
        run: terraform plan   # Fixed output file name
        working-directory: ./Terraform_pipeline
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4  # Fixed action name
        with:
          name: terraform-plan  # Fixed spelling
          path: ./Terraform_pipeline/tfplan.out

      - name: Apply Changes (Main Branch Only)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve ./Terraform_pipeline/tfplan.out  # Fixed command syntax
        working-directory: ./Terraform_pipeline
