name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
   terraform:
   runs-on: ubuntu-latest

permissions:
id-token: write
contents: read

steps:
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1
       with:
            terraform_version: 1.5.0

     - name: Initialize Terraform
       run: terraform init
     - name: Terraform formate 
       run: terrafom fmt -check 

     - name: Validate Terraform
       run: terraform validate

     - name: Plan Infrastructure Changes
       run: terraform plan -out=tfplan

     - name: Upload Artifacts 
       uses: actions/uploadartifacts@v4
       with:
           name: terrafom-plan 
           path: tfplan.out 

     - name: Apply Changes (Main Branch Only)
       if: github.ref == 'refs/heads/main'
       run: terraform apply -auto-approve=tfplan.out 